# Generated by Django 2.2.11 on 2023-09-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_categoryvo_payment_status_prodcutvo_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.Customer')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProdcutVO',
            new_name='ProductVO',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_to_cart', to='sales_app.Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.ProductVO')),
            ],
        ),
    ]
