# Generated by Django 4.0.3 on 2023-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_auto_20230927_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvo',
            name='category',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='CategoryVO',
        ),
    ]
