# Generated by Django 4.0.3 on 2023-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_alter_productvo_category_delete_categoryvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvo',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
